### ISSUE TITLE
Question: can I source the official user menu and only add my commands?

### ISSUE THREAD

**Issue by jirka-h** [musinsky/config#8]
Hello, 

I have followed this [article](https://superuser.com/questions/1716683/midnight-commander-user-menu-command-to-run-external-diff-tool) to add my user menu for `vimdiff`, stored in file `~/.config/mc/menu`:

```
# https://superuser.com/questions/1716683/midnight-commander-user-menu-command-to-run-external-diff-tool

--- vim diff ---
+ ! t t
d   current files/dirs from two panels (use tab to see them)
    vimdiff %f %F

+ t t
d   selected files/dirs from active panel (ONE panel)
    vimdiff %t
```

I also like the official menu which is shipped with `MC` and available under `/etc/mc/mc.menu`. 

Question: Can I source the official menu from the `~/.config/mc/menu`? This way, I would always have the most recent official menu in addition to my own commands. 

Thanks a lot!
Jirka

**Comment by jirka-h** [comment]
Thank you, Jan! 

I have checked the `man` page. I was hoping for something like
```
source /etc/mc/mc.menu
```

For now, I have simply concatenated both files into one. The only drawback is that once `/etc/mc/mc.menu` gets updated with system update, I will not notice the change.

**Comment by musinsky** [comment]
> The only drawback is that once /etc/mc/mc.menu gets updated with system update, I will not notice the change.

Yes, you are right, but in recent years a minimum of new features in system mc menu file (only small corrections).

I personally recommend you rewrite, adapt system menu `/etc/mc/mc.menu` to your user menu `~/.config/mc/menu` and in the future use only user menu with more and more your modifications (for example my [`mc.menu`](https://github.com/musinsky/config/blob/master/MidnightCommander/mc.menu)).

**Comment by jirka-h** [comment]
Yeah, I agree! 

And thanks for sharing your mc.menu file - there are some nice tips, I like the `ExifTool` menu! 

:+1:
